version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - .:/app
    expose:
      - 8080
    env_file:
      - ".env"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - backend

volumes:
  postgres_dev_data:

networks:
  backend:
    driver: "bridge"
