"""Update some tables idk

Revision ID: 304703c87b3c
Revises: fe9c6a379812
Create Date: 2024-02-24 09:47:57.839512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '304703c87b3c'
down_revision: Union[str, None] = 'fe9c6a379812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('donation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('donation', 'search_card_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('donation', 'donor_pet_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('pet', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('pet', 'pet_type_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('unavailable_list', 'pet_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('vaccination', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vaccination', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vaccination', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vaccination', 'pet_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccination', 'pet_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('vaccination', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vaccination', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vaccination', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('unavailable_list', 'pet_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('pet', 'pet_type_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('pet', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('donation', 'donor_pet_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('donation', 'search_card_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('donation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('donation', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
