"""Update search card

Revision ID: fe9c6a379812
Revises: aa1135c74727
Create Date: 2024-02-24 05:39:00.732537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe9c6a379812'
down_revision: Union[str, None] = 'aa1135c74727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_card', 'active_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('search_card', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('search_card', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('search_card', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('search_card', 'recipient_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_card', 'recipient_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('search_card', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('search_card', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('search_card', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('search_card', 'active_until',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
